@startuml spatial_pooler
!include cfg_activity

title Spatial Pooling Algorithm\n\n

start

partition Initialization {
    :init dimensions;
    :init permanences;
    :init connections;
}

partition Overlap {
    while (check for each columns)
        :get connected synapses;
        :get active synapses;
    endwhile (done)
}

partition Inhibition {
    :inhibit;
}

partition Learning {
    :learn;
}

stop
@enduml