@startuml spatial_pooler
skinparam {
    shadowing true
    handwritten false
    titleFontStyle bold
    roundCorner 15
    partitionFontSize 12
    partitionFontStyle italic
    partitionBorderColor DimGray
    partitionBackgroundColor LightGray
}
skinparam activity {
    arrowColor DarkRed
    borderColor GoldenRod
    borderThickness 1
    backgroundColor Gold

    diamondBorderColor GoldenRod
    diamondBorderThickness 1
    diamondBackgroundColor Gold
}

title Spatial Pooling Algorithm\n\n

start

partition Initialization {
    :init dimensions;
    :init permanences;
    :init connections;
}

partition Overlap {
    while (check for each columns)
        :get connected synapses;
        :get active synapses;
    endwhile (done)
}

partition Inhibition {
    :inhibit;
}

partition Learning {
    :learn;
}

stop
@enduml