
@startuml basetypes
skinparam {
    shadowing true
    handwritten false
    titleFontStyle plain
}
skinparam class {
    borderColor GoldenRod
}

class _htmObj_ {
    -_cfg :dict
    -_device :str
    __
    
    +getcfg(key :str) :*
    +getcfgs(void) :dict

    +setcfg(key :str, *)
    +setcfgs(cfgs :dict)

    +append_cfgs(cfgs :dict)

}

class Map {
    -_map :list
    __
    +size
    +map
    __
    +initialize()
}

class Memory {
    -_mem :list
    __
    +size
    +memory
    __
    +initialize()
}

_htmObj_ <|-- Map
_htmObj_ <|-- Memory

@enduml