
@startuml ObjectHTM
skinparam {
    shadowing true
    handwritten false
    titleFontStyle bold
}
skinparam class {
    borderColor DarkGreen
    backgroundColor Ivory
    attributeFontSize 10
}

scale 1.5

class ObjectHTM {
    -_cfg: dict
    __
    .. Getter Functions ..
    
    +cfg(key: str)

    .. Setter Functions ..
    
    +set_cfg(key: str, value)

}
@enduml
